"""add parent_id column to comments

Revision ID: 07694bac74b8
Revises: 5b3a61141d1d
Create Date: 2019-09-16 13:28:31.513363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07694bac74b8'
down_revision = '5b3a61141d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
