"""add_user_follow_table

Revision ID: 3dd3814ea67a
Revises: 
Create Date: 2019-08-30 13:39:47.111511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd3814ea67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('profile_image', sa.Unicode(length=255), nullable=True),
    sa.Column('website', sa.Unicode(length=50), nullable=True),
    sa.Column('bio', sa.Unicode(length=50), nullable=True),
    sa.Column('phone', sa.Unicode(length=20), nullable=True),
    sa.Column('gender', sa.Unicode(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=True),
    sa.Column('following_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
