"""create users table

Revision ID: 530d053a7e19
Revises: 
Create Date: 2019-08-25 16:46:53.758248

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '530d053a7e19'
down_revision = None
branch_labels = None
depends_on = None
GENDER_TYPES = [
    (u'm', u'M'),
    (u'f', u'F'),
    (u'u', u'Unknown'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('website', sa.Unicode(length=50), nullable=True),
    sa.Column('bio', sa.Unicode(length=50), nullable=True),
    sa.Column('phone', sa.Unicode(length=20), nullable=True),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(GENDER_TYPES), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=True),
    sa.Column('following_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follows')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
