"""add users

Revision ID: 609c1bb9e57c
Revises: 
Create Date: 2019-08-25 20:53:28.944607

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '609c1bb9e57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('profile_image', sa.Unicode(length=255), nullable=True),
    sa.Column('website', sa.Unicode(length=50), nullable=True),
    sa.Column('bio', sa.Unicode(length=50), nullable=True),
    sa.Column('phone', sa.Unicode(length=20), nullable=True),
    sa.Column('gender', sa.Unicode(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('following_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
