"""remove post_comment table

Revision ID: f543e415f3c4
Revises: 07694bac74b8
Create Date: 2019-09-16 21:26:54.919683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f543e415f3c4'
down_revision = '07694bac74b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comment')
    op.add_column('comments', sa.Column('post_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    op.create_table('post_comment',
    sa.Column('post_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='post_comment_ibfk_1'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_comment_ibfk_2'),
    sa.PrimaryKeyConstraint('post_id', 'comment_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
